# Generated by Django 3.1.4 on 2020-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201204_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='indice',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
