# Generated by Django 3.1.4 on 2020-12-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categoria_indice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['indice']},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='indice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
