# Generated by Django 3.1.4 on 2020-12-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categoria_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
    ]
