# Generated by Django 3.1.4 on 2020-12-31 14:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.nombre_imagen_producto),
        ),
    ]
