# Generated by Django 3.1 on 2021-01-04 22:50

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono_activo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.nombre_imagen_producto_activo),
        ),
    ]
