# Generated by Django 3.1.5 on 2021-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_categoria_icono_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
