# Generated by Django 3.1.5 on 2021-01-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.TextField(choices=[('kg', 'Kilogramos'), ('un', 'Unidades')], default='kg'),
        ),
    ]
